version: '2'
services:
  web:
    build: .
    container_name: nasse_api
    restart: always
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
